# Generated by Django 2.0 on 2019-07-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialog_label', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialog',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
