# Generated by Django 2.0 on 2019-07-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialog_label', '0002_auto_20190717_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduser',
            name='end',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registereduser',
            name='index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registereduser',
            name='start',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
