# Generated by Django 2.0 on 2019-07-21 08:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dialog_label', '0003_auto_20190718_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduser',
            name='rank',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
