# Generated by Django 2.0 on 2019-07-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialog_label', '0004_registereduser_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialog',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
