# Generated by Django 2.1.5 on 2019-01-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='emotion',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='avatar',
            field=models.ImageField(default='avatar/default.png', upload_to='avatar'),
        ),
    ]
