# Generated by Django 2.0 on 2019-05-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NEUStudent',
            fields=[
                ('uid', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
